# Generated by Django 4.0.2 on 2022-03-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='trans',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
