# Generated by Django 4.0.2 on 2022-04-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tth', '0003_usertravel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('date', models.DateTimeField(blank=True)),
                ('seats', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('utime', models.TimeField(max_length=100)),
            ],
            options={
                'db_table': 'Bus',
            },
        ),
    ]
